
modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="maplestorymod" #mandatory
version="1.16.1-1.0.0" #mandatory
displayName="Maple Story Mod For Minecraft" #mandatory
updateJSONURL="http://myurl.me/" #optional
displayURL="http://example.com/" #optional
logoFile="maplestory.png" #optional
authors="Mingu & Vym" #optional
description='''
Addons From Maplestory for your basic ass Minecraft'''

